name: groceryman
description: A new Flutter application.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_auth: ^1.1.3
  flutter_spinkit: ^4.1.2+1
  font_awesome_flutter: ^8.8.1
  firebase_core: ^1.1.0
  fluttertoast: ^4.0.1
  # firebase_database: ^3.1.5
  cloud_firestore: ^2.0.0
  getwidget: ^1.2.4
  sqflite: ^1.3.1
  url_launcher: 
  razorpay_flutter: ^1.2.1
  path_provider: 
  flutter_email_sender: ^3.0.1
  image_picker: 
  flutter_open_whatsapp: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: 

flutter:
  uses-material-design: true
  fonts:
    - family: sf_pro
      fonts:
        - asset: fonts/SF-Pro-Rounded-Regular.ttf
    - family: Varela_Round
      fonts:
        - asset: fonts/Varela_Round/VarelaRound-Regular.ttf
  assets:
    - images/
    - images/hello.png
